name: exio_energy_extensions
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.0.4
  - ipython-autotime=0.1
  - pandas=1.4.2
  - numpy=1.22.3
  - matplotlib=3.5
  - country_converter=0.7.4
  - tqdm=4.64.0
  - jupyterlab=3.3.4
  - ipykernel=6.13.0
  - python-dotenv=0.19.2
  - openpyxl=3.0.9
  - xlrd=2.0.1
  - pyxlsb=1.0.9
  - black=22.3.0
  - joblib=1.1.0
  - pycodestyle=2.8.0